#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 
bspc config focus_follows_pointer true

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#7aa2f7"  # Cor primária para foco
bspc config normal_border_color "#24283b"   # Cor de fundo ligeiramente mais clara
bspc config active_border_color "#565f89"   # Cor desabilitada para bordas ativas

polybar &
xsetroot -cursor_name left_ptr
feh --bg-scale Imagens/wallpaper.jpg
picom --backend glx
